$RNFirebaseAsStaticFramework = true

# Override Firebase SDK Version
$FirebaseSDKVersion = '7.7.0'

# Override Fabric SDK Version
$FabricSDKVersion = '1.6.0'

# Override Crashlytics SDK Version
$CrashlyticsSDKVersion = '3.1.0'

platform :ios, '10.0'

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'Beitelmal' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-twitter-signin', :path => '../node_modules/react-native-twitter-signin'
  
  # target 'BeitelmalTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #   use_flipper!
  #   post_install do |installer|
  #    flipper_post_install(installer)
  #   end
end

target 'Beitelmal-tvOS' do
  # Pods for Beitelmal-tvOS

  target 'Beitelmal-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
