export default {
  'home': 'home',
  'about': 'about',
  'policy': 'policy',
  'services': 'services',
  'packages': 'package',
  'reports': 'reports',
  'analysis': 'uploads',
  'shortRecommendations': 'evaluation/short',
  'evaluationYears': 'evaluation/long',
  'evaluationMonths': 'evaluation/long/month',
  'evaluationDays': 'evaluation/long/day',
  'recommendations': 'recommendations',
  'sectors': 'sectors',
  'contactUs': 'contactUs',
  'login': 'auth/login',
  'register': 'auth/register',
  'freeRegister': 'auth/freeregister',
  'notifications': 'notification',
}

